update: niggles tweaked

diff --git a/build b/build
--- a/build
+++ b/build
@@ -44,21 +44,21 @@ help () {
 compile () {
   printf "   Configuring\r"
   [[ -a cabal.project.local ]] ||\
-    cabal new-configure --enable-optimisation --enable-library-stripping >\
+    cabal configure --enable-optimisation --enable-library-stripping >\
     install.log
   # [[ -a cabal.project.local ]] || cabal configure --enable-optimisation --enable-library-stripping
   echo "   Configured  "
 
 
   printf "   Building\r"
-  cabal new-build >> install.log
+  cabal build >> install.log
   # cabal build
   echo "   Built    "
 
 
   printf "   Installing\r"
-  fd -t f 'xmonad' dist-newstyle -x mv -u {} $ILOC
-  # fd -tf 'xmonad' dist -x mv -u {} $ILOC
+  # fd -t f 'xmonad' dist-newstyle -x mv -u {} $ILOC
+  fd -tf 'xmonad' dist -x mv -u {} $ILOC
   echo "   Installed "
 }
 
@@ -105,4 +105,5 @@ all () {
 # -- Runtime --------------------------------------------------------------------
 [[ -n $help  ]] && help  && exit
 [[ -n $tidy  ]] && clean && exit
-[[ $OLD > 0  ]] && build || echo "   No compilation required"
+## [[ $OLD > 0  ]] && build || echo "   No compilation required"
+build
